# Generated by Django 2.0.4 on 2018-05-11 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.TextField(max_length=2100)),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_name', models.CharField(default='Quest', max_length=400)),
                ('quest_text', models.TextField(max_length=2100)),
                ('pub_date', models.DateTimeField(default='', verbose_name='date published')),
                ('levels', models.CharField(choices=[('LOW', 'LOW'), ('MIDDLE', 'MIDDLE'), ('HARD', 'HARD')], default='LOW', max_length=6)),
            ],
        ),
    ]
