# Generated by Django 2.0.4 on 2018-07-16 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.TextField(max_length=2100)),
                ('pub_date', models.DateTimeField(default='', verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_text', models.CharField(default='Your purpose', max_length=400)),
                ('pub_date', models.DateField(default='', verbose_name='date')),
                ('who', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_name', models.CharField(default='Quest', max_length=400)),
                ('quest_text', models.TextField(default='text', max_length=2100)),
                ('pub_date', models.DateTimeField(default='', verbose_name='date published')),
                ('done_date', models.DateTimeField(blank=True, null=True)),
                ('levels', models.CharField(choices=[('LOW', 'LOW'), ('MIDDLE', 'MIDDLE'), ('HARD', 'HARD')], default='LOW', max_length=6)),
                ('done_quest', models.BooleanField(default=False)),
                ('today_quest', models.BooleanField(default=False)),
                ('daily_quest', models.BooleanField(default=False)),
                ('who', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Victory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victory_text', models.CharField(default='You the best thing what u want save', max_length=400)),
                ('pub_date', models.DateField(default='', verbose_name='date')),
                ('who', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='quest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.Quest'),
        ),
    ]
