# Generated by Django 2.0.4 on 2018-05-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='quest_name',
            field=models.CharField(default='Quest', max_length=200),
        ),
        migrations.AlterField(
            model_name='quest',
            name='quest_text',
            field=models.TextField(max_length=200),
        ),
    ]
