# Generated by Django 2.0.4 on 2018-05-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20180511_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='done_quest',
            field=models.BooleanField(default=False),
        ),
    ]
