# Generated by Django 2.0.4 on 2018-05-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20180503_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
