# Generated by Django 2.0.4 on 2018-05-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_quest_done_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='today_quest',
            field=models.BooleanField(default=False),
        ),
    ]
