# Generated by Django 2.0.4 on 2018-05-04 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20180503_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='quest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.Quest'),
        ),
    ]
