# Generated by Django 2.0.4 on 2018-05-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_quest_today_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='on_list_today',
            field=models.BooleanField(default=False),
        ),
    ]
