# Generated by Django 2.0.4 on 2018-05-15 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_quest_on_list_today'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='on_list_today',
        ),
    ]
