# Generated by Django 2.0.4 on 2018-05-19 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0006_remove_quest_on_list_today'),
    ]

    operations = [
        migrations.CreateModel(
            name='Victory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victory_text', models.CharField(default='You the best thing what u want save', max_length=400)),
                ('pub_date', models.DateTimeField(default='', verbose_name='date')),
                ('who', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
