# Generated by Django 2.0.4 on 2018-05-27 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0007_victory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='quest',
            name='quest_text',
            field=models.TextField(default='text', max_length=2100),
        ),
        migrations.AddField(
            model_name='daily',
            name='daily_quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Quest'),
        ),
        migrations.AddField(
            model_name='daily',
            name='who',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
