# Generated by Django 2.0.4 on 2018-05-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20180527_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily',
            name='daily_quest',
        ),
        migrations.RemoveField(
            model_name='daily',
            name='who',
        ),
        migrations.AddField(
            model_name='quest',
            name='daily_quest',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Daily',
        ),
    ]
